// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhkbuvqrywmqnpuhexbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoa2J1dnFyeXdtcW5wdWhleGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzkzNDAsImV4cCI6MjA2MTM1NTM0MH0.laFRf6UAuAj7VVpDhutxB-VPTSgRJS4JSksyg2wTgOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);